name: Build Go Tools
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build Tools
        run: |
          go install golang.org/x/tools/gopls@latest
          go install github.com/haya14busa/goplay/cmd/goplay@latest
          go install github.com/josharian/impl@latest
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: go-binaries-windows
          path: C:\Users\runneradmin\go\bin\*.exe
